In [10]:
!pip install kagglehub

Requirement already satisfied: kagglehub in c:\users\lynn\anaconda3\lib\site-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in c:\users\lynn\anaconda3\lib\site-packages (from kagglehub) (0.1.18)
Requirement already satisfied: packaging in c:\users\lynn\anaconda3\lib\site-packages (from kagglehub) (25.0)
Requirement already satisfied: pyyaml in c:\users\lynn\anaconda3\lib\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in c:\users\lynn\anaconda3\lib\site-packages (from kagglehub) (2.32.5)
Requirement already satisfied: tqdm in c:\users\lynn\anaconda3\lib\site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: protobuf in c:\users\lynn\anaconda3\lib\site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (5.29.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\lynn\anaconda3\lib\site-packages (from requests->kagglehub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\lynn\anaconda3\lib\site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\lynn\anaconda3\lib\site-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\lynn\anaconda3\lib\site-packages (from requests->kagglehub) (2025.11.12)
Requirement already satisfied: colorama in c:\users\lynn\anaconda3\lib\site-packages (from tqdm->kagglehub) (0.4.6)

In [11]:
import kagglehub

path = kagglehub.dataset_download("krishanukalita/fmcg-sales-demand-forecasting-and-optimization")
print(" Dataset downloaded to:", path)

 Dataset downloaded to: C:\Users\Lynn\.cache\kagglehub\datasets\krishanukalita\fmcg-sales-demand-forecasting-and-optimization\versions\2

In [12]:
# Installing the libraries 
!pip install pandas scikit-learn sqlalchemy mysql-connector-python openpyxl

Requirement already satisfied: pandas in c:\users\lynn\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: scikit-learn in c:\users\lynn\anaconda3\lib\site-packages (1.8.0)
Requirement already satisfied: sqlalchemy in c:\users\lynn\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: mysql-connector-python in c:\users\lynn\anaconda3\lib\site-packages (9.6.0)
Requirement already satisfied: openpyxl in c:\users\lynn\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lynn\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lynn\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lynn\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lynn\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: scipy>=1.10.0 in c:\users\lynn\anaconda3\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.3.0 in c:\users\lynn\anaconda3\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\lynn\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: greenlet>=1 in c:\users\lynn\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\lynn\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: et-xmlfile in c:\users\lynn\anaconda3\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in c:\users\lynn\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [13]:
# Importing tools
import pandas as pd
from sqlalchemy import create_engine
from urllib.parse import quote_plus   # ← this handles special characters like @

# Credentials
password = "Put_your_password_here"  ← put your password here

# Automatically encoding the @ symbol
encoded_password = quote_plus(password)

# Engine creation
engine = create_engine(f"mysql+mysqlconnector://root:{encoded_password}@127.0.0.1:3306/promotion_engine")

# SQL query
df = pd.read_sql("SELECT * FROM warehouse_sales", engine)

print("Data loaded! Shape:", df.shape)
df.head()   # shows first 5 rows

Data loaded! Shape: (1000, 11)

,id,date,product_category,sales_volume,price,promotion,store_location,weekday,supplier_cost,replenishment_lead_time,stock_level
0,1,2023-05-30,Household,1788.0,7.02,0,Suburban,1,4.39,5.0,91.0
1,2,2022-11-06,Personal Care,893.0,12.56,1,Suburban,6,4.80,5.0,274.0
2,3,2022-11-07,Beverages,128.0,10.63,0,Suburban,0,14.11,7.0,65.0
3,4,2022-11-08,Dairy,248.0,4.03,0,Urban,1,12.37,1.0,359.0
4,5,2022-11-09,Snacks,1902.0,2.20,0,Suburban,2,14.76,2.0,407.0

In [14]:
# Calculating Profit and Promotion ROI
df['profit'] = df['sales_volume'] * (df['price'] - df['supplier_cost'])
df['promo_cost'] = df['supplier_cost'] * df['sales_volume'] * df['promotion'].where(df['promotion'] == 1)

# Promotion ROI = (profit during promo) / promo cost
df['promo_roi'] = df['profit'] / df['promo_cost'].where(df['promo_cost'] > 0)

print("Profit & ROI columns added!")
df[['date', 'product_category', 'price', 'supplier_cost', 'sales_volume', 'promotion', 'promo_cost', 'profit', 'promo_roi']].head(10)

Profit & ROI columns added!

,date,product_category,price,supplier_cost,sales_volume,promotion,promo_cost,profit,promo_roi
0,2023-05-30,Household,7.02,4.39,1788.0,0,NaN,4702.44,NaN
1,2022-11-06,Personal Care,12.56,4.80,893.0,1,4286.40,6929.68,1.616667
2,2022-11-07,Beverages,10.63,14.11,128.0,0,NaN,-445.44,NaN
3,2022-11-08,Dairy,4.03,12.37,248.0,0,NaN,-2068.32,NaN
4,2022-11-09,Snacks,2.20,14.76,1902.0,0,NaN,-23889.12,NaN
5,2022-11-10,Beverages,3.24,4.27,1419.0,0,NaN,-1461.57,NaN
6,2022-11-11,Snacks,5.32,14.56,110.0,1,1601.60,-1016.40,-0.634615
7,2022-11-12,Snacks,7.49,6.75,1635.0,0,NaN,1209.90,NaN
8,2022-11-13,Dairy,8.24,5.54,775.0,0,NaN,2092.50,NaN
9,2022-11-14,Snacks,7.58,1.23,1236.0,1,1520.28,7848.60,5.162602

In [15]:
#Creating & Exporting Master-Data Mapping File (for month-end reporting)
mapping_file = df[['product_category','store_location']].drop_duplicates().reset_index(drop=True)
mapping_file['mapped_category'] = mapping_file['product_category']

mapping_file.to_excel("Master_Data_Mapping.xlsx", index=False)
print("Mater_Data_Mapping.xlsx created!")

Mater_Data_Mapping.xlsx created!

In [16]:
import os
print("Master_Data_Mapping.xlsx should be here, ", os.getcwd())

Master_Data_Mapping.xlsx should be here,  C:\Users\Lynn

In [17]:
#Importing the tools
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

#Defining the features
features = df[['sales_volume', 'profit', 'promo_roi']].fillna(0)

#Scaling
scaler = StandardScaler()
scaled_features = scaler.fit_transform(features)

#Training the model
kmeans = KMeans(n_clusters=3, random_state=42)
df['profit_cluster'] = kmeans.fit_predict(scaled_features)

#Mapping
cluster_names = {0: 'High Profit', 1: 'Medium Profit', 2: 'Low Profit'}
df['cluster_label'] = df['profit_cluster'].map(cluster_names)

print("K-means clustering complete!")
df[['product_category', 'promotion', 'profit', 'promo_roi', 'cluster_label']].head(20)

K-means clustering complete!

   product_category  promotion    profit  promo_roi  cluster_label
0         Household          0   4702.44        NaN     Low Profit
1     Personal Care          1   6929.68   1.616667    High Profit
2         Beverages          0   -445.44        NaN    High Profit
3             Dairy          0  -2068.32        NaN    High Profit
4            Snacks          0 -23889.12        NaN     Low Profit
5         Beverages          0  -1461.57        NaN     Low Profit
6            Snacks          1  -1016.40  -0.634615    High Profit
7            Snacks          0   1209.90        NaN     Low Profit
8             Dairy          0   2092.50        NaN    High Profit
9            Snacks          1   7848.60   5.162602  Medium Profit
10           Snacks          0   1221.22        NaN    High Profit
11            Dairy          0    135.90        NaN    High Profit
12           Snacks          0  -3288.78        NaN     Low Profit
13        Beverages          1   1582.56   0.511675    High Profit
14    Personal Care          0     74.76        NaN    High Profit
15            Dairy          1  -3205.55  -0.358402     Low Profit
16        Household          1  11014.80   2.271186  Medium Profit
17            Dairy          1  -6109.84  -0.420218     Low Profit
18            Dairy          0   1443.62        NaN    High Profit
19        Beverages          0   8312.89        NaN    High Profit

In [18]:
import numpy as np

df['business_profit_label'] = np.where(
    df['promotion'] == 0,
    'Non_promotion', 
    np.where(
        df['profit'] <= 0,
        'Loss/No profit',
    np.where(
        df['profit'] > df['profit'].median(),
        'High Profit', 'Low Profit'
        
        )
    )
)
print("business profit labels created!")

df[['product_category', 'promotion', 'profit', 'promo_roi', 'business_profit_label']].head(15)

business profit labels created!

   product_category  promotion    profit  promo_roi business_profit_label
0         Household          0   4702.44        NaN         Non_promotion
1     Personal Care          1   6929.68   1.616667           High Profit
2         Beverages          0   -445.44        NaN         Non_promotion
3             Dairy          0  -2068.32        NaN         Non_promotion
4            Snacks          0 -23889.12        NaN         Non_promotion
5         Beverages          0  -1461.57        NaN         Non_promotion
6            Snacks          1  -1016.40  -0.634615        Loss/No profit
7            Snacks          0   1209.90        NaN         Non_promotion
8             Dairy          0   2092.50        NaN         Non_promotion
9            Snacks          1   7848.60   5.162602           High Profit
10           Snacks          0   1221.22        NaN         Non_promotion
11            Dairy          0    135.90        NaN         Non_promotion
12           Snacks          0  -3288.78        NaN         Non_promotion
13        Beverages          1   1582.56   0.511675            Low Profit
14    Personal Care          0     74.76        NaN         Non_promotion

In [19]:
#Association Rules 
!pip install mlxtend
from mlxtend.frequent_patterns import apriori, association_rules

promo_basket = (df[df['promotion'] > 0]
                .groupby(['date', 'product_category'])['sales_volume']
                .sum().unstack().reset_index().fillna(0)
                .set_index('date'))

promo_basket = promo_basket.applymap(lambda x: 1 if x > 0 else 0)

frequent_itemsets = apriori(promo_basket, min_support=0.01, use_colnames=True)
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)

print("Association rules generated!")
rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']].head(10)

Requirement already satisfied: mlxtend in c:\users\lynn\anaconda3\lib\site-packages (0.24.0)
Requirement already satisfied: scipy>=1.16.3 in c:\users\lynn\anaconda3\lib\site-packages (from mlxtend) (1.16.3)
Requirement already satisfied: numpy>=2.3.5 in c:\users\lynn\anaconda3\lib\site-packages (from mlxtend) (2.3.5)
Requirement already satisfied: pandas>=2.3.3 in c:\users\lynn\anaconda3\lib\site-packages (from mlxtend) (2.3.3)
Requirement already satisfied: scikit-learn>=1.8.0 in c:\users\lynn\anaconda3\lib\site-packages (from mlxtend) (1.8.0)
Requirement already satisfied: matplotlib>=3.10.8 in c:\users\lynn\anaconda3\lib\site-packages (from mlxtend) (3.10.8)
Requirement already satisfied: joblib>=1.5.2 in c:\users\lynn\anaconda3\lib\site-packages (from mlxtend) (1.5.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\lynn\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\lynn\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\lynn\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\lynn\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\lynn\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\lynn\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\lynn\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\lynn\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lynn\anaconda3\lib\site-packages (from pandas>=2.3.3->mlxtend) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lynn\anaconda3\lib\site-packages (from pandas>=2.3.3->mlxtend) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\lynn\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\lynn\anaconda3\lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (3.5.0)
Association rules generated!

C:\Users\Lynn\AppData\Local\Temp\ipykernel_14128\1140906005.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  promo_basket = promo_basket.applymap(lambda x: 1 if x > 0 else 0)
C:\Users\Lynn\anaconda3\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:175: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

Empty DataFrame
Columns: [antecedents, consequents, support, confidence, lift]
Index: []

In [20]:
# Association Rules (cleaned - no warnings)
from mlxtend.frequent_patterns import apriori, association_rules

promo_basket = (df[df['promotion'] > 0]
                .groupby(['date', 'product_category'])['sales_volume']
                .sum().unstack().reset_index().fillna(0)
                .set_index('date'))

promo_basket = promo_basket.map(lambda x: True if x > 0 else False).astype(bool)

frequent_itemsets = apriori(promo_basket, min_support=0.01, use_colnames=True)
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)

print(" Association rules generated! (warnings removed)")
rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']].head(10)

 Association rules generated! (warnings removed)

Empty DataFrame
Columns: [antecedents, consequents, support, confidence, lift]
Index: []

In [21]:
# Export for Power BI
df.to_csv("clean_promotion_data_with_insights.csv", index=False)
print("Full dataset with BOTH labels + clusters + insights exported!")

Full dataset with BOTH labels + clusters + insights exported!